name: aperturedb-local-dataset-ingestion

services:
  dataset-ingestion:
    build:
      context: ../../apps/dataset-ingestion
    volumes:
      - ../../:/workflows
    environment:
      WF_DATA_SOURCE_GCP_BUCKET: "ad-demos-datasets"
      WF_LOGS_AWS_CREDENTIALS: "aws-credentials"
      DB_HOST: lenz
      DB_PORT: 55551
      PORT: 8080
      PROMETHEUS_PORT: 8001
    command: bash -c "while true; do sleep 1000; done"
    depends_on:
      aperturedb:
        condition: service_started
