name: aperturedb-local-linux

services:
  ca:
    image: alpine/openssl
    restart: on-failure
    command: req -x509 -newkey rsa:4096 -days 3650 -nodes -keyout /cert/tls.key -out /cert/tls.crt -subj "/C=US/O=ApertureData Inc./CN=localhost"
    volumes:
      - ./aperturedb/certificate:/cert

  lenz:
    depends_on:
      ca:
        condition: service_completed_successfully
      aperturedb:
        condition: service_started
    image: aperturedata/lenz:latest
    ports:
      - ${ADB_PORT}:55551
    restart: always
    environment:
      LNZ_HEALTH_PORT: 58085
      LNZ_TCP_PORT: 55551
      LNZ_HTTP_PORT: 8080
      LNZ_ADB_BACKENDS: '["aperturedb:55553"]'
      LNZ_REPLICAS: 1
      LNZ_ADB_MAX_CONCURRENCY: 48
      LNZ_FORCE_SSL: false
      LNZ_CERTIFICATE_PATH: /etc/lenz/certificate/tls.crt
      LNZ_PRIVATE_KEY_PATH: /etc/lenz/certificate/tls.key
    volumes:
      - ./aperturedb/certificate:/etc/lenz/certificate

  aperturedb:
    image: aperturedata/aperturedb-community:latest
    volumes:
      - ./aperturedb/db:/aperturedb/db
      - ./aperturedb/logs:/aperturedb/logs
    restart: always
    environment:
      ADB_KVGD_DB_SIZE: "204800"
      ADB_LOG_PATH: "logs"
      ADB_ENABLE_DEBUG: 1
      ADB_MASTER_KEY: "admin"
      ADB_PORT: 55553
      ADB_FORCE_SSL: false

  webui:
    image: aperturedata/aperturedata-platform-web-private:latest
    restart: always

  nginx:
    depends_on:
      ca:
        condition: service_completed_successfully
    image: nginx
    restart: always
    ports:
      - 8081:80
      - 8443:443
    configs:
      - source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ./aperturedb/certificate:/etc/nginx/certificate

  crawl-website:
    build:
      context: ../../apps/crawl-website
    volumes:
      - ../../:/workflows
    environment:
      WF_LOGS_AWS_CREDENTIALS: "aws-credentials"
      DB_HOST: lenz
      DB_PORT: 55551
      PORT: 8080
      PROMETHEUS_PORT: 8001
    command: bash -c "while true; do sleep 1000; done"
    depends_on:
      aperturedb:
        condition: service_started

configs:
  nginx.conf:
    content: |
      server {
        listen 80;
        listen 443 ssl;
        client_max_body_size 256m;
        ssl_certificate /etc/nginx/certificate/tls.crt;
        ssl_certificate_key /etc/nginx/certificate/tls.key;
        location / {
          proxy_pass http://webui;
        }
        location /api/ {
          proxy_pass http://lenz:8080;
        }
      }

